version: "3"
services:
  frontend:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - /opt/AppFolder/frontend/:/usr/share/nginx/html/
      - /opt/AppFolder/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    environment:
      BACKEND_DNS: http://backend:5000/
    restart: always
  backend:
    image: garvitpatel196/python-app:latest
    ports:
      - "5000:5000"
    restart: always
